### ISSUE TITLE
Convert .RTF document to .MD

### ISSUE THREAD

**Issue by davelab6** [aoifemooney/makingbiorhyme#1]
Quick suggestion :) Instead of an RTF files, you can use Markdown which will pour directly into the blog, and to work on your desktop you can use this libre markdown app that shows you a preview of the formatting as you write it: http://macdown.uranusjr.com

**Comment by aoifemooney** [comment]
Dave I can't write markdown =( I'm seriously struggling here...

**Comment by aoifemooney** [comment]
Ok here's what I really want to say, WHERE do I put it to pour it directly into the blog? I know this probably seems so obvious but i've never worked with code basically at all...

**Comment by davelab6** [comment]
If this isn't quick and easy, then just carry on with RTF files and we can deal with this issue later :) 

Please don't worry :) Nothing is obvious, everything is acquired skills, and this isn't complex code, its more simple 'markup' :)

**Comment by aoifemooney** [comment]
Wait! This MacDown thing actually looks doable... I'll give it a shot! Thanks Dave =) ack, I know it's simple but I think i'm just flapping as I'm not in my comfort zone. I'll get there ;) Thanks for you patience!
