### ISSUE TITLE
Update README with more detailed description

### ISSUE THREAD

**Issue by davelab6** [aoifemooney/makingbiorhyme#5]
https://github.com/aoifemooney/makingbiorhyme/blob/gh-pages/BioRhyme_Libre_Master/README.md has many details about the project, but is missing a 2-3 paragraph description of the design itself, suitable for use in the www.google.com/fonts directory. 
- [ ] Ideally this is written in the 3rd person :)

**Comment by aoifemooney** [comment]
Sorry for the delay! How's this?

"BioRhyme is a display typeface family, intended to work as a set of related but standalone expressive styles for use at larger sizes. It is comprised of two widths and five weights and is supports the Latin 3 character set. 
    Defined by its exaggerated slab serifs, slow curves and playful quirks, BioRhyme comes with a range of alternates to facilitate amping up its quirks where appropriate, while its low contrast allows it to be a functional and readable typeface in short paragraph setting. 
    Its design is an amalgamation of influences including ATF’s 1912 Boston Breton and taking cues from American Typewriter and Archer in its lighter weights, and Clarendon and Rockwell in its blunt slabs and bold weight."

This is in the most recent uploaded release V1.3. Let me know if this is ok or if you think it needs tweaking!

**Comment by davelab6** [comment]
Great! I'll update the readme
